###
GET http://127.0.0.1:8000/content/74d06a24-ae32-4cf3-be20-a8d98be251b4 HTTP/1.1
content-type: application/json



###
GET http://127.0.0.1:8000/factors HTTP/1.1
content-type: application/json




###
GET http://138.68.74.3:8000/content/74d06a24-ae32-4cf3-be20-a8d98be251b4 HTTP/1.1
content-type: application/json
