name: ci

on:
  push:
    branches:
      - "master"
      
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
  
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push test image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: test
          tags: fxxy/news-aggregate-test
          cache-from: type=local,src=/tmp/.buildx-cache
          
      - name: Run Docker Test
        run: |
          echo "${{ secrets.TEST_ENV }}" >> test.env
          cat test.env
          CONTAINERID=$(docker run -d --env-file test.env -e LOG_LEVEL=DEBUG fxxy/news-aggregate-test)
          docker wait $CONTAINERID
          docker logs $CONTAINERID
          STATUS=$(docker container inspect -f '{{.State.ExitCode}}' ${CONTAINERID})
          exit $STATUS
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fxxy/news-aggregate
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
